export const USERNAME_CHANGE = 'USERNAME_CHANGE';
export const USERNAME_VALIDATE = 'USERNAME_VALIDATE';

export const SIGN_IN_SEND_START = 'SIGN_IN_SEND_START';
export const SIGN_IN_SEND_SUCCESS = 'SIGN_IN_SEND_SUCCESS';
export const SIGN_IN_SEND_FAILURE = 'SIGN_IN_SEND_FAILURE';

export const MESSAGES_LIST_SUCCESS = 'MESSAGES_LIST_SUCCESS';
export const MESSAGES_LIST_FAILURE = 'MESSAGES_LIST_FAILURE';

export const MESSAGE_CHANGE = 'MESSAGE_CHANGE';
export const MESSAGE_VALIDATE = 'MESSAGE_VALIDATE';

export const MESSAGE_SEND_START = 'MESSAGE_SEND_START';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const MESSAGE_SEND_FAILURE = 'MESSAGE_SEND_FAILURE';